server:
  port: 9090

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect